# Generated by Django 4.2.2 on 2023-06-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_advantage_delete_user_product_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='img', upload_to='images'),
            preserve_default=False,
        ),
    ]
