# Generated by Django 4.2.2 on 2023-06-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_advantages_product_advantages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advantages',
            new_name='Advantage',
        ),
    ]
