# Generated by Django 4.2.2 on 2023-07-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data_create',
        ),
    ]
