# Generated by Django 4.2.2 on 2023-07-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_order_create_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_order',
            field=models.DateField(auto_now=True),
        ),
    ]
